### ISSUE TITLE
Higlighted text in code blocks isn't visible properly due to dark highlighting color.

### ISSUE THREAD

**Issue by NachiketUN** [ChristianChiarulli/blog#2]

**Comment by ChristianChiarulli** [comment]
I agree. I haven't found a way to change it. There may be some css I could do but I've been too lazy to check it out. I'd rather the gatsby plugin be configurable.

The one I'm using is [here](https://github.com/jamessimone/gatsby-remark-codefence)

I recommend putting an issue there.

**Comment by NachiketUN** [comment]
Oh ok, I'll close this issue then.
