### ISSUE TITLE
Blog isn't working!

### ISSUE THREAD

**Issue by nishu-murmu** [ChristianChiarulli/blog#25]
I tried opening it from different browsers, from different devices, the internet is fine here. I don't know if anyone  got this issue?

</br>

**Edit**: @ChristianChiarulli you changed the domain name of the blog. Which you forgot to mention in the about section of this repo.

**Comment by ChristianChiarulli** [comment]
It will be chrisatmachine.com again, aws is giving me issues.

**Comment by nishu-murmu** [comment]
Got it.
